# Да се напише заявка, която да изведе имената на тези битки,
# за които броят на корабите от тип 'bb', участвали в тази битка,
# е по-голям от броя на корабите от тип 'bc', участвали в същата битка.
# Битки, в които не е участвал нито един кораб, да не се извеждат в резултата.


# FIND COUNT OF ALL SHIPS OF TYPE BB BY BATTLE
SELECT BATTLES.NAME, COUNT(SHIPS.NAME)
FROM CLASSES
   JOIN SHIPS ON CLASSES.CLASS = SHIPS.NAME 
   JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
   JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE CLASSES.TYPE = 'bb'
GROUP BY BATTLES.NAME;

# FIND COUNT OF ALL SHIPS OF TYPE BC BY BATTLE
SELECT BATTLES.NAME, COUNT(SHIPS.NAME)
FROM CLASSES
   JOIN SHIPS ON CLASSES.CLASS = SHIPS.NAME 
   JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
   JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
WHERE CLASSES.TYPE = 'bc'
GROUP BY BATTLES.NAME;

###


SELECT *
FROM 
  (SELECT BATTLES.NAME as battle, COUNT(SHIPS.NAME) as countBB
   FROM CLASSES
   JOIN SHIPS ON CLASSES.CLASS = SHIPS.NAME 
   JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
   JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
   WHERE CLASSES.TYPE = 'bb'
   GROUP BY BATTLES.NAME) AS bb
   JOIN
  (SELECT BATTLES.NAME as battle, COUNT(SHIPS.NAME) as countBC
    FROM CLASSES
    JOIN SHIPS ON CLASSES.CLASS = SHIPS.NAME 
    JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
    JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
    WHERE CLASSES.TYPE = 'bc'
    GROUP BY BATTLES.NAME) AS bc
    ON bb.battle = bc.battle
WHERE bb.countBB > bc.countBC;
